opencontainers/image-tools

image/manifest.go
image/manifest_test.go

Signed-off-by: Lei Jitang <leijitang@huawei.com>
From https://github.com/opencontainers/image-spec/pull/250
Will rebase after #4

Cleanup partially-unpacked directories on failures

---

cmd/oci-unpack/oci-unpack.1.md

Signed-off-by: xiekeyang <xiekeyang@huawei.com>

fix unpack command line

---

Makefile

Signed-off-by: Zhang Wei <zhangwei555@huawei.com>

Fix inconsistent help message in Makefile

---

MAINTAINERS

Signed-off-by: Vincent Batts vbatts@hashbangbash.com

MAINTAINERS: fix Brendan's email

---

cmd/oci-create-runtime-bundle/oci-create-runtime-bundle.1.md
cmd/oci-image-validate/oci-image-validate.1.md
cmd/oci-unpack/oci-unpack.1.md

Some information complements
Signed-off-by: zhouhao zhouhao@cn.fujitsu.com

Information complement

---

cmd/oci-create-runtime-bundle/main.go

main.go:Modify some information

---

cmd/oci-create-runtime-bundle/main.go
cmd/oci-image-validate/main.go
cmd/oci-unpack/main.go

oci-image-tool->oci-create-runtime-bundle
oci-image-tool->oci-unpack
oci-image-tool->oci-image-validate
Signed-off-by: Ling FaKe <lingfake@huawei.com>

cmd: oci-image-tool->oci-xxxx

---

cmd/oci-create-runtime-bundle/main.go
cmd/oci-image-validate/main.go
cmd/oci-unpack/main.go

Signed-off-by: xiekeyang xiekeyang@huawei.com

add version shorthand to commands

---

cmd/oci-create-runtime-bundle/main.go
cmd/oci-image-validate/main.go
cmd/oci-unpack/main.go
image/project.go

This is a draft for #13 .
I intend to move to the code of help inside to the image package, Currently.
Signed-off-by: Sn0rt <wanggh-fnst@cn.fujitsu.com>

Help: with more help information (Issues #13)

---

cmd/oci-create-runtime-bundle/oci-create-runtime-bundle.1.md
cmd/oci-image-validate/oci-image-validate.1.md
cmd/oci-unpack/oci-unpack.1.md

manpage: modify OPTIONS to FLAGS

---

cmd/oci-create-runtime-bundle/main.go
image/image.go

create-main.go: If the dest file does not exist to create.

---

cmd/oci-create-runtime-bundle/oci-create-runtime-bundle.1.md
cmd/oci-image-validate/oci-image-validate.1.md
cmd/oci-unpack/oci-unpack.1.md

Fix information

---

image/autodetect.go

Signed-off-by: Ling FaKe lingfake@huawei.com

autodetect.go: combine two switch cases

---

Makefile

Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

Makefile: include more targets in the help info

---

Makefile

 Makefile: suitable "default" target

---

cmd/oci-image-validate/oci-image-validate.1.md

cmd：fix info

---

Makefile

Makefile: Add missing COMMIT and EPOCH_TST_COMMIT

---

glide.lock
glide.yaml
vendor/github.com/opencontainers/image-spec/schema/fs.go
vendor/github.com/opencontainers/image-spec/schema/validator.go
vendor/github.com/opencontainers/image-spec/specs-go/v1/annotations.go
vendor/github.com/opencontainers/image-spec/specs-go/v1/config.go
vendor/github.com/opencontainers/image-spec/specs-go/version.go

update to image-spec rc7

---

README.md
image/manifest_test.go

https://goreportcard.com/report/github.com/opencontainers/image-tools

Add Go Report Card

---

image/config.go
image/image_test.go

When I execute the create command, there was an error, but there was no error when making the test. So need to improve the test content, and fix the error.

image: avoid panic on nil fields when converting

---

version/version.go

#172 from Mashimiao/cleanup-bundle
#171 from Mashimiao/rm-dup-error
#170 from q384566678/string-fix
#168 from q384566678/fix-annnoation
#165 from q384566678/go-report
#163 from q384566678/image-spec-update
#160 from q384566678/image-spec-up
#158 from q384566678/makefile-fix
#157 from q384566678/image-test-fix
#156 from q384566678/glid-up
#155 from xiekeyang/bump-version
#150 from q384566678/up-image-spec
#141 from Mashimiao/autodetect-add-more-type
#84   from q384566678/test-layout
#51   from q384566678/test-mlist

version： bump to v0.3.0

---

image/layout.go

image: add validation to index.json

---

man/oci-image-tool-create.1.md
man/oci-image-tool-unpack.1.md
man/oci-image-tool-validate.1.md
man/oci-image-tool.1.md

To match Git, which has headers like:
GIT-INIT(1) Git Manual
in git-init(1).

man: Use OCI-IMAGE-TOOL-${COMMAND} in man headers

---

cmd/oci-image-tool/main.go
image/manifest.go
image/manifest_test.go

fix code format

---

README.md
man/oci-image-tool-create.1.md
man/oci-image-tool-unpack.1.md
man/oci-image-tool-validate.1.md

Signed-off-by: Hongchao Deng <hongchaodeng1@gmail.com>
Otherwise it will error:
```
cannot save image with empty image.ref.name
```
Ref: https://github.com/projectatomic/skopeo/issues/446

README.md: fix example

---

cmd/oci-image-tool/validate.go

validate.go: remove continue

---

image/config.go
image/image.go
image/manifest.go
image/manifest_test.go

image: code optimization

---

version/version.go

#143 from Mashimiao/image-optimize-file-searching
#184 from Mashimiao/validate-type-req
#173 from from q384566678/validate-ref-fix
#153 from q384566678/config-type
#146 from q384566678/fix-sub
#169 from q384566678/select-descs
#197 from opencontainers/relax-pullapprove
#174 from q384566678/validate-err-fix
#177 from q384566678/out-test
#195 from hongchaodeng/patch-1
#161 from q384566678/makefile-test-fix
#131 from q384566678/help-test
#189 from q384566678/type-fix
#129 from wking/man-header-cleanup
#194 from Mashimiao/add-mashimiao
#186 from q384566678/mail-map
#42 from wking/remove-before-unpacking
#185 from q384566678/go-version-update
#181 from q384566678/layout-index-validate
#176 from mgoltzsche/175-logrus-lower-case-dependency
Signed-off-by: Zhou Hao <zhouhao@cn.fujitsu.com>

Bump version to v1.0.0-rc1

---

.travis.yml
cmd/oci-image-tool/validate.go
image/autodetect.go
image/image.go
image/image_test.go
image/manifest.go
image/walker.go

Signed-off-by: Zhou Hao <zhouhao@cn.fujitsu.com>

update to golang 1.11
