opencontainers/image-tools

- Makefile
- cmd/oci-create-runtime-bundle/main.go
- cmd/oci-image-validate/main.go
- cmd/oci-unpack/main.go
Signed-off-by: Lei Jitang <leijitang@huawei.com>
Users should have a way to know the spec version and code commit of
the image-tool
````
[lei@fedora image-tools]$ ./oci-create-runtime-bundle --version
commit: 721ba581955c2b8ce1184d7492ed5e3f5ba3e1d4
spec: 0.3.0-dev
[lei@fedora image-tools]$ ./oci-image-validate --version
commit: 721ba581955c2b8ce1184d7492ed5e3f5ba3e1d4
spec: 0.3.0-dev
[lei@fedora image-tools]$ ./oci-unpack --version
commit: 721ba581955c2b8ce1184d7492ed5e3f5ba3e1d4
spec: 0.3.0-dev
````
> Add --version to cmd to show version information

- image/config.go
Instead of using a constant as the runtime-spec
version, user `Version` in the package.
Signed-off-by: Lei Jitang <leijitang@huawei.com>
> Display correct runtime-spec version

- image/descriptor.go
- image/image.go
- image/reader.go
- image/walker.go
Function `(d *descriptor) validate()` is for descriptor variable, with which the exact cas file path is clear. So in this function, it is safely to open the target file, needn't to walk again.
Other walking mechanism is working properly, to need overall refactor, so I don't touch them hastily.
This PR refers to #5 , by @wking, on reading file part. I'm not very sure if this PR is valuable to be accepted individually. Otherwise we should close it and wait for #5 , or please @wking amend this PR with his singed-off?
As to me, I hope a cas reading/writing API can be used to code. 
Signed-off-by: xiekeyang <keyang.xie@gmail.com>
cc @wking @stevvooe
> descriptor validation

- image/image_test.go
migrate patch from https://github.com/opencontainers/image-spec/pull/310
cc @runcom @vbatts @wking @stevvooe
> add unit test for ValidateLayout function

- image/config.go
The image spec requries that
````
MUST be set to layers. Implementations MUST generate an error if
they encounter a unknown value while verifying or unpacking an image.
```
The image-tool should act as the image spec says.
Signed-off-by: Lei Jiang <leijitang@huawei.com>
> Error out if rootfs type is not layers

- Makefile
Make it easy to (re)build a single command without building all of them.  Using main.go as the only prerequisite cuts some corners, but prerequisites for this are hard ;).  With this commit, you can touch `main.go` to force a rebuild.  If that ends up being too awkward, we can make these `.PHONY` targets.
This is the current first commit in #5, to see if [nibbling away at that PR one commit at a time][1] makes review any easier.
[1]: https://github.com/opencontainers/image-tools/pull/5#issuecomment-248781012
> Makefile: Add a pattern rule for oci-* commands

- image/config.go
As I [suggested earlier][1].  Fewer characters for us, and safer quoting for consumers.
[1]: https://github.com/opencontainers/image-tools/pull/32#discussion_r81357093
> image/config: Replace `'%s'` with `%q`

- .pullapprove.yml
Now that this is an independent project.
I'm guessing at the team name, but it matches the [pattern @caniszczyk used for runtime-tools][1].
[1]: https://github.com/opencontainers/runtime-tools/issues/237#issuecomment-255412514
> .pullapprove.yml: Change "image-spec-maintainers" -> "image-tools-maintainers"

- cmd/oci-create-runtime-bundle/main.go
- cmd/oci-unpack/main.go
An error should be reported when the unpack type is not one of the specified two types
> Increase unpack type error judgment

- glide.lock
- glide.yaml
- image/config.go
- image/image_test.go
- image/manifest_test.go
- vendor/github.com/opencontainers/image-spec/schema/fs.go
- vendor/github.com/opencontainers/image-spec/specs-go/v1/descriptor.go
- vendor/github.com/opencontainers/image-spec/specs-go/v1/manifest.go
- vendor/github.com/opencontainers/image-spec/specs-go/v1/manifest_list.go
- vendor/github.com/opencontainers/image-spec/specs-go/v1/mediatype.go
- vendor/github.com/opencontainers/image-spec/specs-go/version.go
- vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
- vendor/github.com/opencontainers/runtime-spec/specs-go/state.go
- vendor/github.com/opencontainers/runtime-spec/specs-go/version.go
[v1.MediaTypeImageLayer ](https://github.com/opencontainers/image-spec/blob/master/specs-go/v1/mediatype.go#L28) in latest image-spec has changed, need to be bumped up to the latest version.
This commit is only focused on bumping the vendored image-spec and runtime-spec to v1.0.0-rc2. `cobra` and `pflag` doesn't tag releases, so I'm pinning this at our currently-vendored commit. I'm not aware of any reason we can't advance this to a later pflag commit, but haven't done enough research to say for sure. 
Signed-off-by: Ye Yin <eyniy@qq.com>
> Bump up runtime-spec/image-spec to the latest version

- cmd/oci-image-validate/main.go
Increases the warning when the ref's use does not conform to the specification
> Validate main.go:add warning

- image/config.go
In this type of authentication is not required, because the json file has been identified [type value](https://github.com/opencontainers/image-spec/blame/master/schema/defs-config.json#L81) ，if not the case, it will never perform type validation.
> config.go:Drop local rootfs.type validation

- cmd/oci-image-validate/oci-image-validate.1.md
There is no default value given to the ref option, so should remove this statement.
> validate.md: delete the ref's default value

- image/manifest.go
In the process of the validation have been carried out for the validation of the [layers,](https://github.com/opencontainers/image-tools/blame/master/image/manifest.go#L83) So they are not needed in the unpack function.
> manifest.go: Remove the extra judgment for layers

- glide.lock
- glide.yaml
- image/config.go
- image/image_test.go
- vendor/github.com/opencontainers/image-spec/schema/fs.go
- vendor/github.com/opencontainers/image-spec/schema/validator.go
- vendor/github.com/opencontainers/image-spec/specs-go/v1/config.go
- vendor/github.com/opencontainers/image-spec/specs-go/v1/descriptor.go
- vendor/github.com/opencontainers/image-spec/specs-go/v1/layout.go
- vendor/github.com/opencontainers/image-spec/specs-go/v1/manifest.go
- vendor/github.com/opencontainers/image-spec/specs-go/v1/manifest_list.go
- vendor/github.com/opencontainers/image-spec/specs-go/versioned.go
Make the following changes according to https://github.com/opencontainers/image-spec/pull/495
> Delete does not exist properties

- image/image_test.go
> image_test.go: Improve the test content

- .tool/lint
- glide.lock
- glide.yaml
- image/image_test.go
- vendor/github.com/opencontainers/go-digest/LICENSE.code
- vendor/github.com/opencontainers/go-digest/LICENSE.docs
- vendor/github.com/opencontainers/go-digest/algorithm.go
- vendor/github.com/opencontainers/go-digest/digest.go
- vendor/github.com/opencontainers/go-digest/digester.go
- vendor/github.com/opencontainers/go-digest/doc.go
- vendor/github.com/opencontainers/go-digest/verifiers.go
- vendor/github.com/opencontainers/image-spec/schema/fs.go
- vendor/github.com/opencontainers/image-spec/specs-go/v1/config.go
- vendor/github.com/opencontainers/image-spec/specs-go/v1/descriptor.go
- vendor/github.com/opencontainers/image-spec/specs-go/v1/layout.go
- vendor/github.com/opencontainers/image-spec/specs-go/v1/manifest.go
- vendor/github.com/opencontainers/image-spec/specs-go/v1/manifest_list.go
- vendor/github.com/opencontainers/image-spec/specs-go/v1/mediatype.go
- vendor/github.com/opencontainers/image-spec/specs-go/version.go
- vendor/github.com/opencontainers/image-spec/specs-go/versioned.go
- vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
- vendor/github.com/opencontainers/runtime-spec/specs-go/state.go
- vendor/github.com/opencontainers/runtime-spec/specs-go/version.go
> vendor/:update

- image/manifest.go
According to [this](https://github.com/opencontainers/image-spec/blame/master/schema/image-manifest-schema.json#L26) ，we can see the minimum length of the layer has been verified in JSON, so the code is redundant.
> manifest.go:remove the size of the layers of judgment

- Makefile
- README.md
- cmd/oci-unpack/oci-unpack.1.md
This is a draft for issue #91 .
Signed-off-by: Sn0rt <wanggh-fnst@cn.fujitsu.com>
> README.md: how to install image-tools (Issue #91)

- image/descriptor.go
Conforming to description 'Before calculating the digest, the size of the content SHOULD be
verified to reduce hash collision space.' at https://github.com/opencontainers/image-spec/blob/master/descriptor.md.
Signed-off-by: Ling FaKe <lingfake@huawei.com>
> descriptor: size verification should be before digest calculation

- glide.lock
- glide.yaml
- image/descriptor.go
- image/image_test.go
- image/manifest_test.go
This is the smallest pivot I could think up (replacing old sha256 imports with go-digest).  But I want the go-digest vendoring to land so I can rebase #5 and #40 on top of it.  And I expect folks who currently prefer other methods for cleaning up the internal image/* code are also interested in go-digest, so I'm filing this PR to get a base that we hopefully all agree on ;).
> image: Port to go-digest

- image/manifest.go
Most recently, the validation was broken because the image-spec was
re-vendored but the code handling MediaType validation was not updated.
This change (among others) broke umoci's tests because we run the
validation code to ensure our images are always valid, and the
validation incorrectly flagged our images as invalid.
Fixes: ff477b3a7e85 ("vendor:update")
Signed-off-by: Aleksa Sarai <asarai@suse.de>
> image: make layer validation work

- Makefile
Modify the command can be reused, the following problems will not occur：
`make: Nothing to be done for 'tools'.`
> Makefile: Add $(TOOLS) to .PHONY

- cmd/oci-create-runtime-bundle/main.go
- cmd/oci-image-validate/main.go
- cmd/oci-unpack/main.go
- version/version.go
During bumping official version, it should not change any code. So, it
has to prepare the version variables, their functions and dummy version
(as 0.0.0-dev) into code. After that is landed, then official versions
can be released.
Signed-off-by: xiekeyang <xiekeyang@huawei.com>
> bump dummy version

- version/version.go
There are merged 219 change-sets since the beginning and cleared the blockers for v0.1.0.
Signed-off-by: xiekeyang <xiekeyang@huawei.com>
> Bump version for v0.1.0

- .gitignore
> ignore generated man files

- .travis.yml
- glide.lock
- glide.yaml
- image/autodetect.go
- image/walker.go
- vendor/github.com/Sirupsen/logrus/LICENSE
- vendor/github.com/Sirupsen/logrus/doc.go
- vendor/github.com/Sirupsen/logrus/entry.go
- vendor/github.com/Sirupsen/logrus/exported.go
- vendor/github.com/Sirupsen/logrus/formatter.go
- vendor/github.com/Sirupsen/logrus/hooks.go
- vendor/github.com/Sirupsen/logrus/json_formatter.go
- vendor/github.com/Sirupsen/logrus/logger.go
- vendor/github.com/Sirupsen/logrus/logrus.go
- vendor/github.com/Sirupsen/logrus/terminal_bsd.go
- vendor/github.com/Sirupsen/logrus/terminal_linux.go
- vendor/github.com/Sirupsen/logrus/terminal_notwindows.go
- vendor/github.com/Sirupsen/logrus/terminal_solaris.go
- vendor/github.com/Sirupsen/logrus/terminal_windows.go
- vendor/github.com/Sirupsen/logrus/text_formatter.go
- vendor/github.com/Sirupsen/logrus/writer.go
supplement of #103. Here we need fix 2:
1. golint failed upper that go version 1.7
2. add logrus package. Refer to https://github.com/opencontainers/image-tools/pull/103#issuecomment-286932965
Signed-off-by: xiekeyang <xiekeyang@huawei.com>
> Add package of Sirupsen/logrus to vendor

- README.md
- glide.lock
- glide.yaml
- vendor/github.com/urfave/cli/LICENSE
- vendor/github.com/urfave/cli/app.go
- vendor/github.com/urfave/cli/category.go
- vendor/github.com/urfave/cli/cli.go
- vendor/github.com/urfave/cli/command.go
- vendor/github.com/urfave/cli/context.go
- vendor/github.com/urfave/cli/errors.go
- vendor/github.com/urfave/cli/flag.go
- vendor/github.com/urfave/cli/flag_generated.go
- vendor/github.com/urfave/cli/funcs.go
- vendor/github.com/urfave/cli/help.go
https://github.com/opencontainers/image-tools/pull/103 adds dependency to urfave/cli without introducing it to /vendor.
Also, update README to reflect the change.
Signed-off-by: Deyuan Deng <deyuan@caicloud.io>
> Add package urfave/cli to vendor

- README.md
> README: fix info

- README.md
- man/oci-image-tool-create.1.md
- man/oci-image-tool-unpack.1.md
- man/oci-image-tool-validate.1.md
> docs: update references to tool name and invocation

- man/oci-image-tool-create.1.md
- man/oci-image-tool-unpack.1.md
- man/oci-image-tool-validate.1.md
- man/oci-image-tool.1.md
> man: remove the extra OPTION

- .pullapprove.yml
This lazily copies image-spec's configuration as updated via
https://github.com/opencontainers/project-template/pull/29 and
https://github.com/opencontainers/image-spec/pull/616
Signed-off-by: Jonathan Boulle <jonathanboulle@gmail.com>
> .pullapprove.yml: Switch to v2 and other updates

- cmd/oci-image-tool/create.go
- cmd/oci-image-tool/unpack.go
- cmd/oci-image-tool/validate.go
This modification can avoid the absence of default values.
> cmd: Modify the assignment of parameters

- cmd/oci-image-tool/validate.go
This was causing panics when validating an image with no refs, hitting this line of code, causing a panic on `out` being nil: https://github.com/opencontainers/image-tools/blob/master/image/image.go#L60
Thanks!
> cmd/oci-image-tool/validate.go: create a logger if none exists.

- Makefile
- image/manifest.go
- image/manifest_test.go
Previously, this would effectively panic on any tar files because it was
expecting a gzip compressed file. This enforces that the `+gzip` media
type exists before enabling gzip decompression.
I also shimmed in some tests by appropriating some others.
Signed-off-by: Erik Hollensbe <github@hollensbe.org>
> image/manifest.go: implement compression detection / mediatype validation

- Makefile
- completions/bash/oci-image-tool
> Add bash-completion for oci-image-tool

- cmd/oci-image-tool/create.go
- cmd/oci-image-tool/unpack.go
- cmd/oci-image-tool/validate.go
oci-image-tool-validate is not correct any more, fix it.
> fix help info for --type option

- image/config.go
- image/descriptor.go
- image/image.go
- image/image_test.go
- image/manifest.go
- image/manifest_test.go
- image/walker.go
This is a #121 follow-up PR, make the image-tool work with -rc5. Sorry so late update.
> make the image-tool work with -rc5

- image/image_test.go
- image/manifest_test.go
> tiny fix: format code and tfix

- version/version.go
#142 from Mashimiao/tfix-format
#144 from q384566678/up-validate
#140 from Mashimiao/fix-help-info
#148 from q384566678/up-runtime-spec
#132 from q384566678/fix-glide
#139 from Mashimiao/add-bash-completion
#135 from erikh/fix-tar-files
#145 from q384566678/zhou-hao
#134 from erikh/fix-logger
#137 from q384566678/value-test
#138 from jonboulle/master
#133 from Mashimiao/makefile-add-missing-evars
#130 from q384566678/zz-test
#136 from squeed/tar-streams
#128 from q384566678/fix-man
#127 from q384566678/reandme-fix
#126 from ddysher/update-vendor
#124 from xiekeyang/logrus
#103 from q384566678/main-test
#123 from q384566678/fix-list
#121 from q384566678/bump-version
#119 from Mashimiao/fix-ignore
> Bump version v0.2.0

- image/image.go
- image/layout.go
Increase the validation of the files contained in the layout.
Including `blobs` , `oci-layout` and `index.json` files.
> image: add image layout validation 

- cmd/oci-image-tool/create.go
- cmd/oci-image-tool/unpack.go
- completions/bash/oci-image-tool
- image/descriptor.go
- image/image.go
- image/image_test.go
- image/index.go
- man/oci-image-tool-create.1.md
- man/oci-image-tool-unpack.1.md
if the ManifestList exists, it needs to be validated
Signed-off-by: zhouhao zhouhao@cn.fujitsu.com
> Add index.json validation

- cmd/oci-image-tool/create.go
- cmd/oci-image-tool/unpack.go
- image/descriptor.go
Without this fix, result was:
```
$ oci-image-tool create --platform linux  busybox-oci testdir
creating failed: index.json: descriptor not found
index.json: descriptor not found
```
duplicated errors are printed and we don't know which descriptor can't be found.
> remove duplicated error printing

- image/image.go
> image.go: Simplified type declaration

- image/image.go
If any error occurs, we should cleanup the bundle we created. If not, this may confuse users.
> cleanup created bundle when creating failed

- cmd/oci-image-tool/create.go
- cmd/oci-image-tool/unpack.go
- cmd/oci-image-tool/validate.go
- completions/bash/oci-image-tool
- image/autodetect.go
- image/image.go
- image/layout.go
- image/walker.go
- man/oci-image-tool-create.1.md
- man/oci-image-tool-unpack.1.md
- man/oci-image-tool-validate.1.md
> autodetect: add support for zip and rar archive type

- image/manifest.go
Implementing the logic that is in-flight with opencontainers/image-spec#317, but [using recursive removal](https://github.com/opencontainers/image-spec/pull/317/files#r79214718).  GNU tar has a `--recursive-unlink` option that's not enabled by default, with the motivation being something like “[folks would be mad if we blew away a full tree and replaced it with a broken symlink](https://www.gnu.org/software/tar/manual/html_node/Dealing-with-Old-Files.html)”.  That makes sense for working filesystems, but we're building the rootfs from scratch here so losing information is not a concern.  This commit always uses recursive removal to get that old thing off the filesystem (whatever it takes ;).
The exception to the removal is if both the tar entry and existing path occupant are directories. …
> image/manifest: Recursively remove pre-existing entries when unpacking

- cmd/oci-image-tool/main.go
Due to negligence in the loss of this part of #103 , now restored.
> main: restore more help information

- Makefile
> Makefile: add gofmt and govet to test

- image/doc.go
> doc.go: Perfect description

- .pullapprove.yml
There has been a request to relax the number of LGTMs in the
tools projects to help improve merge rate.
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>
> Relax LGTMs

- cmd/oci-image-tool/create.go
- cmd/oci-image-tool/unpack.go
- cmd/oci-image-tool/validate.go
- image/descriptor.go
- image/image.go
- image/image_test.go
- man/oci-image-tool-create.1.md
- man/oci-image-tool-unpack.1.md
- man/oci-image-tool-validate.1.md
Increase the search conditions, you can better retrieve descriptor.
Resolved when the search is not unique or non-existent.
cc/ @opencontainers/image-tools-maintainers 
Fixes #164
> Modify the ref option

- cmd/oci-image-tool/create.go
- cmd/oci-image-tool/unpack.go
- cmd/oci-image-tool/validate.go
> cmd: small fixes

- cmd/oci-image-tool/create.go
- cmd/oci-image-tool/unpack.go
- cmd/oci-image-tool/validate.go
When the input ref content is repeated, should output a prompt.
> validate: Increase ref content repeat detection

- cmd/oci-create-runtime-bundle/oci-create-runtime-bundle.1.md
- cmd/oci-image-tool/validate.go
- cmd/oci-image-validate/oci-image-validate.1.md
- cmd/oci-unpack/oci-unpack.1.md
- completions/bash/oci-image-tool
- image/autodetect.go
- man/oci-image-tool-validate.1.md
1. spec says any extra fields in json file can be ignored, so I think
we can't clearly distingish which type the text file is, we'd better remove
autodetect for text files.
2. without audotdetect, we must requrie to user to set file type for validation
> validate: remove autodetect for type and add require limit

- image/config.go
- image/descriptor.go
- image/manifest.go
- image/walker.go
walkFunc is inefficient. If we knows which file to read, there is no need to call w.walk().
For imageLayout, w.find() will improve the file searching speed.
> image: optimize file searching
